### ISSUE TITLE
Redesign GameScene with assets

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_ios_app#18]
Replace the text-based gameplay with images.

- [x] Trim unnecessary text
- [x] Prepare assets
- [x] Represent player's hand with images
- [x] Represent current bet with images

**Comment by adrian-golian** [comment]
Implemented the image-based gameplay.
![IMG_3678](https://user-images.githubusercontent.com/10632991/80897788-e6cc0900-8cfc-11ea-9d59-e16f872db04b.PNG)

**Comment by maciej-pomykala** [comment]
How is history handled in this scene?

**Comment by adrian-golian** [comment]
Only the last bet is pulled out of history and displayed.

**Comment by adrian-golian** [comment]
We could probably add a popup to display the history in text. Based on user feedback, the doesn’t seem to be a need. If there’s a need to, we can open a new issue for it.

**Comment by maciej-pomykala** [comment]
I'll close this then and open a new one
