### ISSUE TITLE
Fix reported UI glitches

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_ios_app#41]
- [ ] Fix bet image matching (e.g. colour hearts instead of diamonds)
- [x] Fix the share label reappearing 
- [x] Fix the "You lost" displaying repeatedly (that's the "Game over" behaviour, not "You lost")
- [x] Display "You win" instead of "Game over" (if won)
- [x] Don’t display cards if `Game.status == .finished`

**Comment by adrian-golian** [comment]
<img width="860" alt="Screenshot 2020-05-10 at 18 35 22" src="https://user-images.githubusercontent.com/10632991/81505050-09f24c00-92ed-11ea-9217-1a3cdfc9da68.png">

**Comment by maciej-pomykala** [comment]
Well, at least... you call a spade a spade.
