### ISSUE TITLE
Enable creating and joining public games

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_ios_app#71]
The app could have a lobby with public games listed there (enabling the user to join a game by clicking on it) and enable the admin to make a game public.

At the moment, it's most convenient for a Shiny app user to receive the pure game UUID from the game organiser, while an iOS app user would like to receive the `blef:///` link. With public games support in both apps, there would be no need to send and then modify links to organise cross-platform games.

Even a one-platform game could be made simpler if links did not need to be sent, but rather only one in-game click was needed from each player for everyone to join. That would be most useful if players were coordinating games on a conference call.

This feature would be in addition to the usual invite links

**Comment by adrian-golian** [comment]
Broken up into #82 and #83 - closing this issue.
